#SPRING CONFIGURATION
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: H@Dialect
        format_sql: true

#LOGGING CONFIGURATION
logging:
  level:
    org:
      hibernate:
        sql: info

