spring:
  application:
    name: feedback-service
  profiles:
    active: dev
  liquibase:
    change-log: classpath:/db/changelog/changelog.yml
    parameters:
      default-schema: ${spring.liquibase.default-schema}

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus